### PR TITLE
add a userid capability

### PR DESCRIPTION
**Pull request by juhp**
This depends on podenv/hub#44

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
Thank you for proposing this new capability. Here are some initial thoughts:

https://github.com/podenv/podenv/blob/a1f4c9cf33cdefd13c22c8f6e0831e6d421caab6/src/Podenv/Application.hs#L100-L102 makes this capability implicit when the image or the app defines an home path. I wonder if we should make this behavior explicit instead. Though perhaps its not worth the trouble to change that now.

Also considering the actual runtime setting (https://github.com/podenv/podenv/blob/53e445567c3474decd3ce9cf8e2c57a5b65a8f1a/src/Podenv/Runtime.hs#L102), should we rename it `keep-uid` instead?

And finally, the `capsToggle` order matter, thus I think this should be defined before the root capability, so that setting `--root` takes precedence. Or perhaps podenv could fail with an error indicating that both root and userid can't be set at the same time. Initially I implemented capability parameters so that we can define `--user root` or `--user keep-id` and avoid such conflict, but the implementation was a bit complex and a simpler list of boolean is probably better, even though it enables impossible state.

**Comment by TristanCacqueray** [comment]
Or perhaps you could just re-use the existing implicit behavior, e.g. setting the `home` attribute of the application (for example to `Some "/root"`) would be identical to enabling this cap. Thus, this could simply be a CLI toggle without using a new capability. If that works for you, here is how that could be done:

- Add a new `--keep-uid` toggle here: https://github.com/podenv/podenv/blob/2812db8a7c4ce9fd05c57c1e066c59426db22aad/src/Podenv/Main.hs#L118
- Add a new attribute to `RuntimeEnv` here: https://github.com/podenv/podenv/blob/2812db8a7c4ce9fd05c57c1e066c59426db22aad/src/Podenv/Runtime.hs#L44-L48
- Set the value from the CLI here: https://github.com/podenv/podenv/blob/2812db8a7c4ce9fd05c57c1e066c59426db22aad/src/Podenv/Main.hs#L177
- Then activate the podman cli argument for userid in the Nothing case of: https://github.com/podenv/podenv/blob/2812db8a7c4ce9fd05c57c1e066c59426db22aad/src/Podenv/Runtime.hs#L106.

I like this approach better because it keeps the capability list shorter.

**Comment by juhp** [comment]
Thanks for the responses.

I feel that uid and "home" dir should be separately configurable.

I am not opposed to an implicit (or explicit) default behavior, but I can image cases where one wants a uid not obviously associated with some "home" dir. Perhaps `HOME`/owner could be used for this though? (My HOME is `/var/home/...` and currently ignored.)

Anyway I do feel something should be done to enable uid mapping. I am afk today, but will try to look at and think more on this soon.

**Comment by TristanCacqueray** [comment]
Please re-open if this is still needed. I wonder if that could be implemented without adding a new capability.

**Pull request closed without merging**
